{
 "title": "Cypress",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Visited Pages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cypress_event_page_loaded_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"cypress\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Visited Pages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cypress_event_page_loaded_total"
    }
   ]
  }
 ]
}